"""add age field to employees

Revision ID: 1b70ed4c5e78
Revises: df9ad224afec
Create Date: 2026-08-31 16:47:40.664009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b70ed4c5e78'
down_revision: Union[str, Sequence[str], None] = 'df9ad224afec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'age')
    # ### end Alembic commands ###
