"""add unique constraint to phone

Revision ID: 7c06a11c9147
Revises: 1b70ed4c5e78
Create Date: 2026-09-10 11:01:02.782949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c06a11c9147'
down_revision: Union[str, Sequence[str], None] = '1b70ed4c5e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.create_unique_constraint(None, 'employees', ['email'])
    op.create_unique_constraint(None, 'employees', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_constraint(None, 'employees', type_='unique')
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    # ### end Alembic commands ###
